version: '3.8'

services:
  claude-workflow:
    build: .
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./logs:/app/logs
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
    networks:
      - workflow-network

  workflow-scheduler:
    build: .
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: python3 src/workflow_runner.py --scheduled
    restart: unless-stopped
    networks:
      - workflow-network

networks:
  workflow-network:
    driver: bridge
